### ISSUE TITLE
Wallet-api registration-defaults.conf fails to load

### ISSUE THREAD

**Issue by niwim** [walt-id/waltid-identity#475]
The registration-defaults.conf fails to load and since it is set to [optional](https://github.com/niwim/waltid-identity/blob/a7f5b5a6cc26b301fd54cd37cc37df72579c09fe/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/config/ConfigManager.kt#L51) testing fails to catch the issue.

Error:

```
4141 [main] DEBUG id.walt.webwallet.config.ConfigManager - Loading optional configuration: "registration-defaults" (RegistrationDefaultsConfig)...
4187 [main] INFO id.walt.webwallet.config.ConfigManager - OPTIONAL configuration "registration-defaults" not loaded: Failed requirement. [This is not a mistake if you are not using named feature. The feature will not be available when not configured.]
```

The issue is related to the [RegistrationDefaultsConfig](https://github.com/niwim/waltid-identity/blob/a7f5b5a6cc26b301fd54cd37cc37df72579c09fe/waltid-wallet-api/src/main/kotlin/id/walt/webwallet/config/RegistrationDefaultsConfig.kt#L11) implementation. Seems to be that the conf-file is in Hocon format and the RegistrationDefaultsConfig assumes it to be JSON.

**Comment by mikeplotean** [comment]
Hi @niwim, this is fixed now as part of the bigger refactoring work concerning the entire configuration management which now is replaced by an advanced feature flag system - https://github.com/walt-id/waltid-identity/pull/454.
Thank you for reporting that and for your contribution.

**Comment by niwim** [comment]
Hi, I've tested the latest build and I still cannot load the config for the Vault integration. I'm getting a similar issue as before where Hoplite is throwing an error because of "Failed Requirement"

```
ERROR [                main] :        ConfigManager : ---- vvv Configuration error for "registration-defaults" vvv ----
Could not load configuration for "registration-defaults" (RegistrationDefaultsConfig): java.lang.IllegalArgumentException: Failed requirement.
```

Looking at the new implementation I would expect to see a similar issue as the KeyGenerationRequest class [expects a JSON ](https://github.com/walt-id/waltid-identity/blob/e357231a2c046198f166d87c70c54e5f69538574/waltid-libraries/waltid-crypto/src/commonMain/kotlin/id/walt/crypto/keys/KeyGenerationRequest.kt#L11) for the config whilst the registration-default is written in Hocon format.

**Comment by niwim** [comment]
Hi @mikeplotean, sorry for hassling you. I've created this [PR](https://github.com/walt-id/waltid-identity/pull/531) as a possible fix.

**Comment by mikeplotean** [comment]
@niwim thanks a lot for your contribution and for reporting the issues
apparently this has been already fixed in https://github.com/walt-id/waltid-identity/pull/534
